### ISSUE TITLE
Cleanup dropStudent(Student s) method

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#12]
Comments on dropStudent(Student s) method. 

  * Does unnecessary work by copying everything into a new array then back to the original. Instead, copy into a new array what is wanted and the assign studentRoster to the new array.
  * Copies null into unused elements of the array. Not needed since nobody will ever look at them.
  * Uses a variable for "success" when simply returning true or false will suffice and makes for better readability in this case.
  * **Suggestion**, in the method, find the position of the Student passed, then pass that as a parameter to the dropStudent(int position) method. I think it's a good idea since the project notes made a point of saying there could (should) be more than one way to do the dropStudent method and it's good code reuse.

**Comment by mdasc2** [comment]
Could you write what you would expect the code to be for the first bullet point? I believe currently the code is fine for this assignment, but yeah you could just copy what you needed with conditional into another array and point the old one to the new one. It is more efficient.

Yeah I agree with the null, I'll fix that one.

I've always been taught to use a variable since just declaring true/false was deemed bad conventionally? If no one cares about it in workspace then I've been living a lie.

I believe your misinterpreting the project notes for dropStudent, I think you can just do the method any way you want it with the header dropStudent(Student s). Not that he wants a dropStudent(int position) method

**Comment by karlnicholas** [comment]
Re bullet point 1, consider this:

    Student[] newRoster = new Student[rosterSize];
    int i= 0;
    for(Student cs: currentRoster) {
       if ( cs.equals(currentRoster[i]) continue;
       newRoster[i++] = cs;
       if ( i >= studentCount ) break;
    }
    currentRoster = newRoster;  // assign new array to instance variable.
    return true;

I think that will work. So, it creates a new array, copies only into it what you want, and then assigns the new array to the object's instance variable. The old array gets garbage collected.

**Comment by karlnicholas** [comment]
Re other dropStudent. On reading closer and checking answer Prof. gave in forum, I agree that there is no need for two dropStudent signatures. I recommend deleting the dropStudent(int position) and optimizing current code.

**Comment by mdasc2** [comment]
I cleaned it up and made it look nicer, however in my current loop there is a bit of redundancy in that it loops rosterCopy[j] = studentRoster[j]; until j < studentCounter, which isn't necessary and only works out because I assign studentRoster to RosterCopy so they are the same thing and it doesn't matter that it runs. 

I can only think of using a break statement here to prevent that or doing a j++ which I did do. I'm wondering if there was a better way to do it.

Sorry if I didn't articulate the problem well.

**Comment by karlnicholas** [comment]
Hi Andrew, 

    for(Student s: currentRoster) 

is an enhanced for loop, or a for-each loop. This is covered in the text in section 7.7 or on the slides on page 39. I didn't watch the videos either, too time consuming. 

If I understand your question correctly, I used a break statement to exit the loop once everything is copied, instead of doing a loop inside of a loop. I used a continue statement to skip over the student to be dropped, basically continue on to the next student.

Looking closer, I notice my code was broken on the if statement. Was
    if ( cs.equals(currentRoster[j])) continue;  // or something

should be
    if ( cs.equals(s)) continue;

It should be testing if the cs (current student to be copied) is equal to the student to be dropped (passed as s). If so, continue on to the next student to be copied. Break, or stop copying, when studentCounter is reached. I updated the code in the prior comment.

Your code is definitely cleaner and not doing unnecessary work, but still a little obfuscated because of the loop inside the loop. Basically, your inner loop takes over from the outer loop, which is not intuitive and therefore "obfuscated". Its better if loops go through their full count or break out on a condition. The loop within a loop construct suggests that you are actually doing a loop within a loop, but since you're not it's hard to read. I would prefer if you would revisit that again. Also, note issue #10.

**Comment by mdasc2** [comment]
I believe I've edited it to your liking

**Comment by karlnicholas** [comment]
Very nicely done. I hope this is to your liking as well. 

BTW: When creating a new array, all the references are set to null. So the unused elements of the roster will be null by this new method. Clearing out unused references (e.g., setting them to null) is not unimportant. If a program does not use a reference in an array that reference will not be able to be garbage collected since it is still referenced by an active array. This impacts memory performance, so paying attention to *all* the references in an array can be important.

**Comment by mdasc2** [comment]
Alright, thanks.

I feel like I've learned quite a bit from this assignment, some things that I wasn't actively paying attention too.
