### ISSUE TITLE
course.setMaxStudents(0); causes an infite loop.

### ISSUE THREAD

**Issue by karlnicholas** [CS111B-META-SUMMER-2016/Team1-Project2#13]
course.setMaxStudents(0); causes an infinite loop. 

Test with TestModel class. Assign to anyone.

**Comment by mdasc2** [comment]
I just got rid of the while loop for it, its not needed if the programmer who uses this class wants to force a re-entry of the maxStudents, he should do the while loop in the driver. Otherwise I think the while loop has no chance of breaking out of the infinite loop. Since you can never reenter setMaxStudents.
